<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <NoWarn />
	  <WarningLevel>4</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <NoWarn />
	  <WarningLevel>4</WarningLevel>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="LambdaPulse.Tests" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="PulseInject" Version="0.1.0-beta.1" />
	</ItemGroup>

</Project>
